name: Build/release

on:
  push:
    branches:
      - '**'     # any branch
    tags:
      - 'v*'     # e.g., v1.0.0
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: NPM MAKE
        run: npm run make-win32

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swim-results-helper-application-win32-build
          path: out/make

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
